config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :flats, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :bookings, only: :create
  end


  namespace :host do
    resources :flats, only: [:index]
  end

  resources :pictures, only: [:destroy]
  patch "pictures/:id/make_primary", to: "pictures#make_primary", as: "make_primary"

  resources :bookings, only: :index

  patch 'bookings/:id/approve', to: 'bookings#approve', as: :approve_booking
  patch 'bookings/:id/reject', to: 'bookings#reject', as: :reject_booking

  get 'bookings/:flat_id', to: 'bookings#flat', as: :bookings_for_flat

end

app/models/booking.rb
class Booking < ApplicationRecord
  BOOKING_STATUSES = ["pending", "approved", "rejected"]

  belongs_to :user
  belongs_to :flat

  validates :status, presence: true, inclusion: { in: BOOKING_STATUSES }

  def primary_picture
    primary = flat.pictures.where(is_primary: true).first
    primary.nil? ? false : primary.url
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  skip_before_action :authenticate_user!, only: :create
  # creates a new booking
  def create
    # Check to see if the user is registered/logged in
    if current_user.nil?
       # Store the form data in the session so we can retrieve it after login
       session[:booking] = [booking_params, params[:flat_id]]
       # Redirect the user to register/login
       redirect_to new_user_registration_path
    else
      # If the user is already logged in, proceed as normal
      @booking = Booking.new(booking_params)
      @booking.flat = Flat.find(params[:flat_id])
      @booking.user = current_user
      @booking.save
      flash[:notice] = "Sweet, booking request submitted :)"
      redirect_to bookings_path
    end
  end

  # lists the travellers bookings
  def index
    @bookings = Booking.where(user: current_user)
  end

  # lists bookings for a flat
  def flat
    @flat = Flat.find(params[:flat_id])
    @bookings = @flat.bookings
  end

  # approves a booking
  def approve
    @booking = Booking.find(params[:id])
    @booking.status = "approved"
    @booking.save
  end

  # rejects a booking
  def reject
    @booking = Booking.find(params[:id])
    @booking.status = "rejected"
    @booking.save
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/views/bookings/approve.js.erb
const buttonsDivApproved = document.querySelector("[data-flat-id='<%= @booking.id %>']");

const statusSpanApproved = document.querySelector("[data-flat-status-id='<%= @booking.id %>']");

buttonsDivApproved.innerText = "";

statusSpanApproved.innerText = "approved";

app/views/bookings/flat.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="booking-container">

        <% if current_user.is_host %>
          <div class="row">
            <div class="col-xs-8 col-xs-offset-2 text-center">
              <h2>Your bookings</h2>
            </div>
          </div>

          <div class="row">
            <div class="col-xs-8 col-xs-offset-2 text-center">
              <% flat = Flat.find(params[:flat_id]) %>
              <h4>Your flat  <i>"<%= flat.name %>"</i>  has <strong><%= flat.bookings.length %> bookings </strong> in total </h4>
            </div>
          </div>

          <div class="row">
            <% @bookings.each do |booking| %>
              <div class="col-xs-3">
                <div class="booking-card">
                    <div class="booking-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(
                        <% if booking.primary_picture %>
                          <%= booking.primary_picture %>
                        <% else %>
                          <%= "https://a0.muscache.com/4ea/air/v2/pictures/5fc9f2c6-271a-45b5-bdc9-807edeefbd87.jpg?t=r:w2500-h1500-sfit,e:fjpg-c90" %>
                        <% end %>);">
                    </div>

                    <div class="booking-info">
                        <small id="booking-date">FROM <%= booking.start_date.strftime("%m/%d/%Y") %> TO <%= booking.end_date.strftime("%m/%d/%Y") %></small>
                        <br>
                        <small>Status: <span data-flat-status-id="<%= booking.id %>"><%= booking.status %></span></small>
                    </div>

                    <div class="booking-status" data-flat-id="<%= booking.id %>">
                      <% if booking.status == "pending" %>
                         <div class="confirm-buttons-row">
                            <%= link_to 'Reject', reject_booking_path(booking), method: 'patch', remote: true, class: 'btn btn-sm btn-danger'%>
                            <%= link_to 'Approve', approve_booking_path(booking), method: 'patch', remote: true, class: 'btn btn-sm btn-primary'%>
                          </div>
                      <% end %>
                    </div>

                  </div>
                </div>
              <% end %>
            </div>

        <% else %>
          <h2 class="text-center"><%= "You do not have any pending booking confirmations." %></h2>
        <% end %>


      </div>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="booking-container">
        <div class="row">
          <div class="col-xs-12">
            <h1 class="text-center">My bookings</h1>
          </div>
        </div>

        <div class="row">
          <% @bookings.each do |booking| %>
          <div class="col-xs-6 col-md-3 col-lg-3 space-between-cards">
            <div class="booking-card">
              <div class="booking-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(
                <% if booking.primary_picture %>
                <%= booking.primary_picture %>
                <% else %>
                <%= "https://a0.muscache.com/4ea/air/v2/pictures/5fc9f2c6-271a-45b5-bdc9-807edeefbd87.jpg?t=r:w2500-h1500-sfit,e:fjpg-c90" %>
                <% end %>);">
              </div>
              <div class="booking-info">
                <small id="booking-date">FROM <%= booking.start_date.strftime("%m/%d/%Y") %> TO <%= booking.end_date.strftime("%m/%d/%Y") %></small>
                <br>
                <small><%= booking.flat.name %></small>
                <br>
              </div>
              <div class="booking-status">
                <% if booking.status == "approved" %>
                <span class="badge green-badge-confirmation"><%= booking.status.upcase %></span>
                <% else %>
                <span class="badge red-badge"><%= booking.status.upcase %></span>
                <% end %>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/reject.js.erb
const buttonsDivReject = document.querySelector("[data-flat-id='<%= @booking.id %>']");

const statusSpanReject = document.querySelector("[data-flat-status-id='<%= @booking.id %>']");

buttonsDivReject.innerText = "";

statusSpanReject.innerText = "rejected";