config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :flats, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :bookings, only: :create
  end


  namespace :host do
    resources :flats, only: [:index]
  end

  resources :pictures, only: [:destroy]
  patch "pictures/:id/make_primary", to: "pictures#make_primary", as: "make_primary"

  resources :bookings, only: :index

  patch 'bookings/:id/approve', to: 'bookings#approve', as: :approve_booking
  patch 'bookings/:id/reject', to: 'bookings#reject', as: :reject_booking

  get 'bookings/:flat_id', to: 'bookings#flat', as: :bookings_for_flat

end

app/views/shared/_filter.html.erb
<div class="filter">
    <%= form_tag flats_path, method: :get, class: "input-form" do %>
    <%= text_field_tag :address,
      params[:address],
      class: "form-center",
      placeholder: "Location" %>
    <%= text_field_tag :min_price,
      params[:min_price],
      class: "form-center",
      placeholder: "min price" %>
    <%= text_field_tag :max_price,
      params[:max_price],
      class: "form-center",
      placeholder: "max price" %>
    <%= text_field_tag :guests,
      params[:guests],
      class: "form-center",
      placeholder: "Guests" %>
    <%= submit_tag("filter", :id=>"button-resize", :class=>"btn-medium", :name=>"submit") %>
    <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_flats_form.erb
  <% if @flat.new_record? %>
  <h2>Create your flat</h2>
  <% else %>
  <h2>Edit your flat details</h2>
  <% end %>
  <%= simple_form_for( @flat, html: { class: "justitia-user-form justitita-box"}) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests%>
  <%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id} %>
  <%= f.input :address, id: 'flat_address' %>
  <%= f.input :latitude, as: :hidden %>
  <%= f.input :longitude, as: :hidden %>
  <%= f.simple_fields_for :pictures do |p| %>
  <div id=picture-fields>
    <div>
      <label class='form-control-label' for='Picture'> Add pictures </label>
      <%= p.file_field :picture %>
      <%= p.input :picture_cache, as: :hidden %>
    </div>
    <div class ='supporting-pictures' >
      <% if @flat.new_record? %>
      <label class='form-control-label' style="display: none;" id='supporting-picture-label'> Supporting pictures </label>
      <% end %>
      <div id="secondary-pictures">
      </div>
      <div class=flat-form-buttons>
        <button type="button" class="btn-medium align-add-picture-button" id="more-pictures-button">Add more pictures</button>
        <div class="form-actions">
          <%= f.submit "Submit", class: "btn-medium align-submit-button" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_flats_form_edit.html.erb
<div class="container">
  <h2>Edit your flat details</h2>
  <%= simple_form_for( @flat, html: { class: "justitia-user-form justitita-box"}) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests%>
  <%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id} %>
  <%= f.input :address, id: 'flat_address' %>
  <%= f.input :latitude, as: :hidden %>
  <%= f.input :longitude, as: :hidden %>
  <%= f.simple_fields_for :pictures do |p| %>
  <div id=picture-fields>
    <div>
      <label class='form-control-label' for='Picture'> Add pictures </label>
      <%= p.file_field :picture %>
      <%= p.input :picture_cache, as: :hidden %>
    </div>
    <div class ='supporting-pictures' >
      <div id="secondary-pictures">
      </div>
      <div class=flat-form-buttons>
        <button type="button" class="btn-medium" id="more-pictures-button">Add more pictures</button>
        <div class="form-actions">
          <%= f.submit "Submit changes", class: "btn-medium red" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>


<div class="container">
  <h2>Edit your pictures</h2>
  <div class="justitia-user-form justitita-box">
    <div class="row">
      <% if  @flat.pictures.first.nil? %>
      OOOH NOOOOOHHHH! You do not have any pictures yet! Please add some pictures above, my love.
      <%end %>
      <% @flat.pictures.each do |picture|%>
      <div class="col-xs-4">
        <div data-picture-id=<%= picture.id %> class="edit-image-container">
          <%= cl_image_tag(picture.url,
          width: 400, height: 300, crop: :fill) %>
          <% if picture.is_primary? %>
          <span class="badge top-right-badge">Primary</span>
          <%end %>
        </div>
        <div class="edit-picture-footer" data-picture-id=<%= picture.id %>>
          <%= link_to picture_path(picture), method: :delete, remote: true, data: { confirm: "Are you sure?" } do %>
          <i class="fas fa-trash-alt delete-image black-text">Delete image</i>
          <% end %>
          <% if !picture.is_primary? %>
          <%= link_to make_primary_path(picture), method: :patch, remote: true, data: { confirm: "Are you sure?" }  do %>
          <i class="fas fa-edit main-image black-text">Change to primary</i>
          <% end %>
          <%end %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flats_form_edit_pictures.html.erb
<h2>Edit your pictures</h2>
  <div class="justitia-user-form justitita-box">
    <div class="row">
      <% if  @flat.pictures.first.nil? %>
      OOOH NOOOOOHHHH! You do not have any pictures yet! Please add some pictures above, my love.
      <%end %>
      <% @flat.pictures.each do |picture|%>
      <div class="col-xs-4">
        <div data-picture-id=<%= picture.id %> class="edit-image-container">
          <%= cl_image_tag(picture.url,
          width: 400, height: 300, crop: :fill) %>
          <% if picture.is_primary? %>
          <span class="badge top-right-badge">Primary</span>
          <%end %>
        </div>
        <div class="edit-picture-footer" data-picture-id=<%= picture.id %>>
          <%= link_to picture_path(picture), method: :delete, remote: true, data: { confirm: "Are you sure?" } do %>
          <i class="fas fa-trash-alt"></i><span class="delete-image black-text">Delete image</span>
          <% end %>
          <% if !picture.is_primary? %>
          <%= link_to make_primary_path(picture), method: :patch, remote: true, data: { confirm: "Are you sure?" }  do %>
          <i class="fas fa-edit"></i><span class="main-image black-text">Change to primary</span>
          <% end %>
          <%end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_flats_form_new.html.erb
<div class="container">

  <h2>Create your flat</h2>

  <%= simple_form_for( @flat, html: { class: "justitia-user-form justitita-box"}) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests%>
  <%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id} %>
  <%= f.input :address, id: 'flat_address' %>
  <%= f.input :latitude, as: :hidden %>
  <%= f.input :longitude, as: :hidden %>


  <%= f.simple_fields_for :pictures do |p| %>
  <div id=picture-fields>

    <div>
      <label class='form-control-label' for='Picture'> Primary picture </label>
      <%= p.file_field :picture %>
      <%= p.input :picture_cache, as: :hidden %>
    </div>
    <div class ='supporting-pictures' >
      <label class='form-control-label' style="display: none;" id='supporting-picture-label'> Supporting pictures </label>
      <div id="secondary-pictures">
      </div>
      <div class = flat-form-buttons>
        <button type="button" class="btn-medium" id="more-pictures-button">Add more pictures</button>
        <div class="form-actions">
          <%= f.submit "Add your flat", class: "btn-medium red" %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <% end %>

</div>

app/views/shared/_footer.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="footer">
      <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
      </div>
      <div class="footer-copyright">
        This footer is made with <i class="fas fa-heart"></i> by Justitia Riders
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag("logo.png") %>
  </a>

  <!-- Right Navigation -->

  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? %>

    <div class="navbar-welcome-message">Welcome <%= current_user.first_name.capitalize %>!</div>

        <% if current_user.is_host %>
          <%= link_to "Add a Flat", new_flat_path, class: "navbar-wagon-item navbar-wagon-link" %>
         <%= link_to "My flats", host_flats_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <% else %>
         <%= link_to "Become a host", new_flat_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <% end %>
      <% if !current_user.bookings.first.nil?  %>
    <%= link_to "My bookings", bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
      <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %>

    <% else  %>
    <%= link_to "Become a host", new_flat_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Log in", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Sign up", new_user_registration_path, class: "btn-medium" %>
    <% end  %>
  </div>


  <!-- Dropdown appearing on mobile only -->

  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
        <div class="navbar-welcome-message-small">Welcome <%= current_user.first_name.capitalize %>!</div>

         <% if current_user.is_host %>
            <li><%= link_to "Add a Flat", new_flat_path %></li>
           <li><%= link_to "My flats", host_flats_path %></li>
          <% else %>
           <li><%= link_to "Become a host", new_flat_path %></li>
          <% end %>
        <% if !current_user.bookings.first.nil?  %>
        <li><%= link_to "My bookings", bookings_path %></li>
        <% end %>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else  %>
        <li><%= link_to "Become a host", new_flat_path %></li>
        <li><%= link_to "Log in", new_user_session_path %></li>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
        <% end  %>

      </ul>
    </div>
  </div>
</div>