config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :flats, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :bookings, only: :create
  end


  namespace :host do
    resources :flats, only: [:index]
  end

  resources :pictures, only: [:destroy]
  patch "pictures/:id/make_primary", to: "pictures#make_primary", as: "make_primary"

  resources :bookings, only: :index

  patch 'bookings/:id/approve', to: 'bookings#approve', as: :approve_booking
  patch 'bookings/:id/reject', to: 'bookings#reject', as: :reject_booking

  get 'bookings/:flat_id', to: 'bookings#flat', as: :bookings_for_flat

end

app/models/flat.rb
class Flat < ApplicationRecord
  class CoordsError < StandardError; end
  belongs_to :user
  has_many :pictures, dependent: :destroy
  has_many :bookings, dependent: :destroy
  validates :name, presence: true, length: { minimum: 6, too_short: "%{count} characters is the minimum allowed" }, allow_blank: false
  validates :name, presence: true, length: { maximum: 100, too_long: "%{count} characters is the maximum allowed" }
  validates :address, presence: true, allow_blank: false
  # validates :description, presence: true, length: { maximum: 200, too_long: "%{count} characters is the maximum allowed" }
  validates :price_per_night, presence: true, allow_nil: false, numericality: { only_integer: true, greater_than: 0 }
  validates :number_of_guests, presence: true, numericality: { only_integer: true, greater_than: 0 }, allow_nil: false

  geocoded_by :address

  before_save :validate_coords

  # to be used when saving flats from the command line instead of save
  def geo_save
    geocode
    save
  end

  def validate_coords
    raise CoordsError if latitude.nil? || longitude.nil?
  end

  def primary_picture_url
    pic = pictures.where(is_primary: true).first
    pic.nil? ? false : pic.url
  end

  def count_approved_bookings
    bookings.where(status: "approved").length
  end

  def count_pending_bookings
    bookings.where(status: "pending").length
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :index]
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
    if params[:address].present?
      sql_query = "address @@ :query"
      @flats = @flats.where(sql_query, query: "%#{params[:address]}%")
    end
    if params[:min_price].present?
      sql_query = "price_per_night > :query"
      @flats = @flats.where(sql_query, query: "#{params[:min_price]}")
    end
    if params[:max_price].present?
      sql_query = "price_per_night < :query"
      @flats = @flats.where(sql_query, query: "#{params[:max_price]}")
    end
    if params[:guests].present?
      sql_query = "number_of_guests >= :query"
      @flats = @flats.where(sql_query, query: "#{params[:guests]}")
    end
    # build markers based on search
    @flats_markers = @flats.where.not(latitude: nil, longitude: nil)

    @markers = @flats_markers.map do |flat|
      {
        lng: flat.longitude,
        lat: flat.latitude
      }
    end
  end

  def new
    @flat = Flat.new
  end

  def show
    @flat = Flat.find(params[:id])
    @markers = [{
      lng: @flat.longitude,
      lat: @flat.latitude
    }]
    @booking = Booking.new
  end

  def create
    @created_pictures = params["flat"]["pictures"]
    @flat = Flat.new(flat_params)
    @flat.user = current_user
    if @flat.save
      if @created_pictures["picture"] || @created_pictures["picture0"]
        @created_pictures.each do |key, value|
          unless key.include? "cache"
            create_picture(key, value)
          end
        end
        set_primary_picture
      end
      user_as_host!(@flat.user)
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @created_pictures = params["flat"]["pictures"]
    if @flat.update(flat_params)
      @created_pictures.each do |key, value|
        unless key.include? "cache"
          create_picture(key, value)
        end
      end
      redirect_to flat_path(@flat)
    else
      render :edit
    end
  end

  def destroy
    Flat.destroy(@flat[:id])
    respond_to do |format|
      format.js
    end
  end

  private

  def user_as_host!(user)
    user.is_host = true
    user.save
  end

  def create_picture(_key, value)
    picture = Picture.new(url: value)
    picture.flat = @flat
    picture.save
  end

  def set_primary_picture
    first_picture = @flat.pictures.first
    first_picture.is_primary = true
    first_picture.save
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :latitude, :longitude, :description, :price_per_night, :number_of_guests, :pictures)
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end
end

app/controllers/host/flats_controller.rb
class Host::FlatsController < ApplicationController
  before_action :authenticate_user!
  def index
    @flats = current_user.flats
  end
end

app/views/host/flats/index.html.erb
<div class="message-container">

  <h1>Manage your Flats</h1>
  <% @flats.each do |flat| %>
  <div class="message justitita-box" data-flat-id="<%= flat.id %>">
    <div class="flat-description">
      <% if flat.primary_picture_url %>
      <%= cl_image_tag flat.primary_picture_url, class: "img-size" %>
      <% else %>
      <%= image_tag "https://vignette.wikia.nocookie.net/theislands/images/f/fd/House_placeholder.jpg/revision/latest?cb=20140101201028", class: "img-size" %>
      <% end %>
      <div class="message-body">
        <h3> <%= flat.name %> </h3>
        <p><%= flat.address %></p>
      </div>
    </div>
    <div class="status">
      <p id="approved">Confirmed bookings: <%= flat.count_approved_bookings %></p>
      <p id="pending">Pending bookings: <%= flat.count_pending_bookings %></p>
    </div>
    <div class="actions">
      <ul class="list-inline">
        <li><%= link_to "Edit", edit_flat_path(flat), class: "btn-medium" %></li>
        <li><%= link_to "Manage my booking", bookings_for_flat_path(flat), class: "btn-medium" %></li>
        <li><%= link_to "Delete", flat_path(flat),
        method: :delete,
        remote: true,
        data: { confirm: "Are you sure?" }, class: "btn-medium red"%></li>
      </ul>
    </div>
    <div id="notification">
      <img src="https://www.colorcombos.com/images/colors/FC7405.png">
      <p> <%= flat.count_pending_bookings %> </p>
    </div>
  </div>
  <% end %>

</div>